# Generated by Django 5.2 on 2025-04-09 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regiment',
            fields=[
                ('regiment_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('regiment_type', models.CharField(choices=[('Танк', 'Танкын Баталион'), ('Артилери', 'Артилерийн Дивизион'), ('Мотобуудлага', 'Мотобуудлагын Баталион')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=3, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('rank', models.CharField(choices=[('Б/ч', 'Байлдагч'), ('А/б', 'Ахлах Байлдагч'), ('Д/т', 'Дэд Түрүүч'), ('Т/ч', 'Түрүүч'), ('А/т', 'Ахлах Түрүүч')], default='Б/ч', max_length=20)),
                ('face_encoding', models.BinaryField(blank=True, null=True)),
                ('active_status', models.BooleanField(default=True, help_text='Whether this personnel is currently active in service')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('regiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='inventory.regiment')),
            ],
            options={
                'verbose_name_plural': 'Personnel',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=6, unique=True, verbose_name='Серийн дугаар')),
                ('bolt_number', models.CharField(max_length=6, unique=True, verbose_name='Замгийн дугаар')),
                ('case_number', models.CharField(max_length=6, unique=True, verbose_name='Хайрцаг ангийн тагны дугаар')),
                ('weapon_model', models.CharField(choices=[('АКМ', 'Автомат'), ('АКС', 'Автомат'), ('СВД', ''), ('ПКТ', '')], max_length=10)),
                ('qr_code', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'In Maintenance'), ('decommissioned', 'Decommissioned')], default='available', max_length=20)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_weapon', to='inventory.personnel')),
            ],
        ),
    ]
