# Generated by Django 5.2 on 2025-05-05 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regiment',
            fields=[
                ('regiment_id', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Салбар нэгжийн дугаар')),
                ('regiment_type', models.CharField(choices=[('Танк', 'Танкын Баталион'), ('Артилери', 'Артилерийн Дивизион'), ('Мотобуудлага', 'Мотобуудлагын Баталион')], max_length=30, unique=True, verbose_name='Салбар нэгж')),
            ],
            options={
                'verbose_name': 'Салбар нэгж',
                'verbose_name_plural': 'Салбар нэгжүүд',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=3, unique=True, verbose_name='Алба хаагчийн дугаар')),
                ('first_name', models.CharField(max_length=100, verbose_name='Алба хаагчийнн нэр')),
                ('last_name', models.CharField(max_length=100, verbose_name='Алба хаагчийн овог')),
                ('rank', models.CharField(choices=[('Б/ч', 'Байлдагч'), ('А/б', 'Ахлах Байлдагч'), ('Д/т', 'Дэд Түрүүч'), ('Т/ч', 'Түрүүч'), ('А/т', 'Ахлах Түрүүч')], default='Б/ч', max_length=20, verbose_name='Цол')),
                ('face_encoding', models.BinaryField(blank=True, null=True, verbose_name='Царайны өгөгдөл')),
                ('active_status', models.BooleanField(default=True, verbose_name='Алба хааж байгаа төлөв')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн огноо')),
                ('regiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='inventory.regiment', verbose_name='Салбар нэгж')),
            ],
            options={
                'verbose_name': 'Алба хаагч',
                'verbose_name_plural': 'Алба хаагчид',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=6, unique=True, verbose_name='Серийн дугаар')),
                ('bolt_number', models.CharField(max_length=6, unique=True, verbose_name='Замгийн дугаар')),
                ('case_number', models.CharField(max_length=6, unique=True, verbose_name='Хайрцаг ангийн тагны дугаар')),
                ('weapon_model', models.CharField(choices=[('АКМ', 'Автомат'), ('АКС', 'Эвхдэг автомат'), ('СВД', 'Дурантай буу'), ('ПКТ', 'Пулемёт')], max_length=10, verbose_name='Бууны загвар')),
                ('qr_code', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='QR код')),
                ('status', models.CharField(choices=[('available', 'Идвэхитэй'), ('assigned', 'Хариуцагчтай'), ('maintenance', 'Засварт байгаа'), ('decommissioned', 'Актлагдсан')], default='available', max_length=20, verbose_name='Төлөв')),
                ('acquisition_date', models.DateField(blank=True, null=True, verbose_name='Олгосон огноо')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Засварт орсон огноо')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Тэмдэглэл')),
                ('location', models.CharField(choices=[('in', 'Хадгалагдасан'), ('out', 'Гарсан')], default='in', help_text='Галт зэвсгийн байршил', max_length=10, verbose_name='Галт зэвсгийн байршил')),
                ('assigned_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_weapon', to='inventory.personnel', verbose_name='Хариуцагч')),
            ],
        ),
    ]
