# Generated by Django 5.2 on 2025-04-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_weapon_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='location',
            field=models.CharField(choices=[('in', 'Хадгалагдасан'), ('out', 'Гарсан')], default='in', help_text='Галт зэвсгийн байршил', max_length=10),
        ),
    ]
