# Generated by Django 5.2 on 2025-04-21 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_weapon_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Алба хаагч', 'verbose_name_plural': 'Алба хаагчид'},
        ),
        migrations.AlterModelOptions(
            name='regiment',
            options={'verbose_name': 'Салбар нэгж', 'verbose_name_plural': 'Салбар нэгжүүд'},
        ),
        migrations.AlterField(
            model_name='personnel',
            name='active_status',
            field=models.BooleanField(default=True, verbose_name='Алба хааж байгаа төлөв'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Алба хаагчийнн нэр'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='id_number',
            field=models.CharField(max_length=3, unique=True, verbose_name='Алба хаагчийн дугаар'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Алба хаагчийн овог'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='rank',
            field=models.CharField(choices=[('Б/ч', 'Байлдагч'), ('А/б', 'Ахлах Байлдагч'), ('Д/т', 'Дэд Түрүүч'), ('Т/ч', 'Түрүүч'), ('А/т', 'Ахлах Түрүүч')], default='Б/ч', max_length=20, verbose_name='Цол'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='regiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='inventory.regiment', verbose_name='Салбар нэгж'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Бүртгэсэн огноо'),
        ),
        migrations.AlterField(
            model_name='regiment',
            name='regiment_id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Салбар нэгжийн дугаар'),
        ),
        migrations.AlterField(
            model_name='regiment',
            name='regiment_type',
            field=models.CharField(choices=[('Танк', 'Танкын Баталион'), ('Артилери', 'Артилерийн Дивизион'), ('Мотобуудлага', 'Мотобуудлагын Баталион')], max_length=30, unique=True, verbose_name='Салбар нэгж'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='Олгосон огноо'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Засварт орсон огноо'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='status',
            field=models.CharField(choices=[('available', 'Идвэхитэй'), ('assigned', 'Хариуцагчтай'), ('maintenance', 'Засварт байгаа'), ('decommissioned', 'Ашиглагдахаа больсон')], default='available', max_length=20, verbose_name='Төлөв'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_model',
            field=models.CharField(choices=[('АКМ', 'Автомат'), ('АКС', 'Автомат'), ('СВД', 'Дурантай буу'), ('ПКТ', 'Пулемёт')], max_length=10, verbose_name='Бууны загвар'),
        ),
    ]
