# Generated by Django 5.2 on 2025-04-14 08:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_alter_weapon_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('personnel_id', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('ERROR', 'Error')], max_length=10)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FaceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('personnel_id', models.CharField(max_length=20, unique=True)),
                ('face_embedding', models.BinaryField(blank=True, null=True)),
                ('face_image_path', models.CharField(blank=True, max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaceRegistrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.CharField(blank=True, max_length=100, null=True)),
                ('successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_registrations', to='inventory.personnel')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeaponTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('checkout', 'Check Out'), ('checkin', 'Check In'), ('reassign', 'Reassignment'), ('maintenance', 'Maintenance')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('face_confidence_score', models.FloatField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, help_text='Admin user who verified this transaction', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('auth_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='face_authentication.authenticationlog')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.personnel')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.weapon')),
            ],
            options={
                'verbose_name': 'Weapon Transaction',
                'verbose_name_plural': 'Weapon Transactions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
