# Generated by Django 5.2 on 2025-04-09 01:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRegistrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('successful', models.BooleanField(default=True)),
                ('registered_by', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('checkin', 'Check In'), ('checkout', 'Check Out'), ('reassign', 'Reassignment')], max_length=20)),
                ('face_confidence_score', models.FloatField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, help_text='Admin user who verified this transaction', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.personnel')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.weapon')),
            ],
            options={
                'ordering': ['-transaction_time'],
            },
        ),
    ]
