# Generated by Django 5.2 on 2025-05-05 12:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('personnel_id', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('ERROR', 'Error')], max_length=10)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FaceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('personnel_id', models.CharField(max_length=20, unique=True)),
                ('face_embedding', models.BinaryField(blank=True, null=True)),
                ('face_image_path', models.CharField(blank=True, max_length=255)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaceRegistrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.CharField(blank=True, max_length=100, null=True)),
                ('successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_registrations', to='inventory.personnel')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeaponTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('checkout', 'Гарсан'), ('checkin', 'Орсон'), ('reassign', 'Дахин хуваарилсан')], max_length=20, verbose_name='Төрөл')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Огноо')),
                ('face_confidence_score', models.FloatField(blank=True, null=True, verbose_name='Царай танилтын оноо')),
                ('verified_by', models.CharField(blank=True, help_text='Оролт, гаралтыг хянасан хүн', max_length=100, null=True, verbose_name='Хянагч')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Тэмдэглэл')),
                ('auth_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='face_authentication.authenticationlog')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.personnel')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.weapon')),
            ],
            options={
                'verbose_name': 'Оролт гаралтын бүртгэл',
                'verbose_name_plural': 'Оролт гаралтын бүртгэлүүд',
                'ordering': ['-timestamp'],
            },
        ),
    ]
