# Generated by Django 5.2 on 2025-04-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapontransaction',
            name='transaction_type',
            field=models.CharField(choices=[('checkout', 'Check Out'), ('checkin', 'Check In'), ('reassign', 'Reassignment')], max_length=20),
        ),
    ]
