# Generated by Django 5.2 on 2025-04-21 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_authentication', '0002_alter_weapontransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapontransaction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Оролт гаралтын бүртгэл', 'verbose_name_plural': 'Оролт гаралтын бүртгэлүүд'},
        ),
        migrations.AlterField(
            model_name='weapontransaction',
            name='face_confidence_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Царай танилтын оноо'),
        ),
        migrations.AlterField(
            model_name='weapontransaction',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Тэмдэглэл'),
        ),
        migrations.AlterField(
            model_name='weapontransaction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Огноо'),
        ),
        migrations.AlterField(
            model_name='weapontransaction',
            name='transaction_type',
            field=models.CharField(choices=[('checkout', 'Гарсан'), ('checkin', 'Орсон'), ('reassign', 'Дахин хуваарилсан')], max_length=20, verbose_name='Төрөл'),
        ),
        migrations.AlterField(
            model_name='weapontransaction',
            name='verified_by',
            field=models.CharField(blank=True, help_text='Оролт, гаралтыг хянасан хүн', max_length=100, null=True, verbose_name='Хянагч'),
        ),
    ]
